- name: Deploy User | Create
  user: name="{{ deploy_user}}" groups="sudo" shell="/bin/bash"

- name: Deploy User | Add RSA key to the remote host
  authorized_key: user="{{ deploy_user }}" key="{{ lookup('file', deploy_user_key)}}"

- name: Deploy User | Remove password
  command: "passwd {{ deploy_user }} -d"

- name: Deploy User | Update sudoers file 
  lineinfile: dest="/etc/sudoers" insertafter="EOF" line='{{ deploy_user }} ALL=(ALL) NOPASSWD:ALL' state="present"
  when: deploy_user_sudo
